apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
      name: worker
    spec:
      containers:
      - name: worker
        image: testacr01fr4t.azurecr.io/worker:1.5

 