apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: db
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: "postgres"

        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: db-password-secret
              key: db-password
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data

      volumes:
      - name: db-data
        emptyDir: {}
      