apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: result
  name: result
spec:
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
      name: result
    spec:
      containers:
      - name: result
        image: parshchakurkar/result:1.4
        ports:
        - containerPort: 4000
 