apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: vote
  name: vote
spec:
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
      name: vote
    spec:
      containers:
      - name: vote
        image: parshchakurkar/vote:1.2
        ports:
        - containerPort: 80
